name: Flujo de Integración Continua
on: [push]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.tests.txt

      - name: Ejecutar tests
        run: pytest --junitxml=result.xml

      - name: Recopilar resultado de los tests
        uses: mikepenz/action-junit-report@v3.7.1
        if: success() || failure()
        with:
          report_paths: './result.xml'

      - run: rm ./result.xml

      - name: Autenticarse en el registry
        if: github.ref_type == 'tag'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Construir imagen
        if: github.ref_type == 'tag'
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/franciscomoma/curso-ejemplos-ci/ejemplo-python:${{ github.ref_name }}
            ghcr.io/franciscomoma/curso-ejemplos-ci/ejemplo-python:latest